package scanner

// Harness-leak detection: the two shapes an agent harness stamps onto a public
// artefact that its repository never asked for.
//
// An autonomous cloud run in a sibling repository posted pull-request bodies and
// issue comments carrying a live SESSION URL and a tool's default "Generated
// with …" attribution FOOTER. The commit messages stayed clean, because the
// commit trailer is the one surface the repository's own convention reached; the
// footer and the link were appended when the forge artefact was created, OUTSIDE
// the model's own text, and GitHub's public edit history kept the pre-scrub
// revision (iss-178). The class was later found in this repository too, that time
// MODEL-authored — an agent reasoning from a generic default. A detector cannot
// tell the two apart after the fact, and does not need to: the shape is the
// finding, whoever wrote it.
//
// The class lives HERE, in the canonical set, and nowhere else. Folded into
// DefaultPatterns it reaches every store-before-commit consumer (capture, memory,
// history, launch) for free, and the two surfaces that judge committed text —
// `abcd lint`'s privacy rule and record/docs-lint — select it by kind. Two
// definitions of a leak is how one of them comes to mean something weaker.
//
// Neither pattern is anchored with `^`. That is deliberate and load-bearing: the
// adjacency probe (scanner.go) re-compiles every pattern's body inside `\A(?:…)`
// and runs it against a WINDOW of the line, where a `^` would match at the window
// start rather than at the line start — turning a line-anchored pattern into an
// anywhere-in-the-line one at exactly the offsets the probe visits. The footer's
// line-start requirement is expressed in its SkipAt instead, which sees the real
// line and the real offset.

import (
	"regexp"
	"strings"
)

// Harness-leak kinds.
const (
	kindHarnessSessionURL = "harness:session_url"
	kindHarnessFooter     = "harness:attribution_footer"
)

var (
	// A live agent-session URL: a http(s) URL whose path carries a `session`
	// segment followed by an id. The regex is the CANDIDATE generator only — the
	// id it captures is then required to be OPAQUE (opaqueSessionID), because a
	// documentation URL such as .../blog/using-agent-session-management-and-1m
	// satisfies every structural test a regex can state and is not a session link
	// at all. That URL is in this repository's own research notes, so the
	// distinction is not hypothetical.
	//
	// No trailing \b, for the reason the token patterns state: the trailing class
	// contains '-', so a boundary after the last character can be unsatisfiable
	// and would silently drop the whole match. The leading \b, the scheme, and the
	// id minimum bound it; greedy matching redacts the full URL.
	// The optional :port and the `?session_id=` query spelling are both covered:
	// a harness that puts the id in a query parameter or serves from a non-default
	// port leaks exactly as much as one that puts it in the path.
	harnessSessionURLRe = regexp.MustCompile(`(?i)\bhttps?://[a-z0-9.-]+(?::[0-9]{1,5})?/[a-z0-9._~%/+?&=-]*session[_/=-](?:id=)?[A-Za-z0-9-]{12,}`)
	// The id a candidate URL ends in, for the opacity test.
	sessionIDTailRe = regexp.MustCompile(`(?i)session[_/=-](?:id=)?([A-Za-z0-9-]+)$`)
	// A UUID session id, the other spelling a harness uses.
	sessionUUIDRe = regexp.MustCompile(`^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$`)

	// A tool's default attribution footer. The SHAPE is ported from this repo's
	// own attribution gate (scripts/check-attribution.sh GENERATED_RE), which was
	// widened three times as each spelling got through it: the robot emoji on
	// either side of a markdown emphasis run of one to three markers, and
	// "generated with" or "generated by" followed by a markdown link. A different
	// tool's footer is caught as readily as the one that prompted it.
	harnessFooterRe = regexp.MustCompile(`(?:🤖[ \t]*)?(?:[_*]{1,3})?(?:🤖[ \t]*)?[Gg]enerated (?:with|by) \[`)

	// The host of any http(s) URL in a span, for the reserved-documentation check.
	urlHostRe = regexp.MustCompile(`(?i)\bhttps?://([a-z0-9.-]+)`)
	// What may precede a footer on its own line: indentation, blockquote markers,
	// and at most one list marker. Anything else is prose, and prose quoting the
	// banned shape is documentation.
	footerLinePrefixRe = regexp.MustCompile(`^[ \t>]*(?:(?:[-*+]|[0-9]{1,3}\.)[ \t]+)?[ \t>]*$`)
)

// reservedDocTLDs are the documentation/test TLDs an example may use (RFC
// 6761/2606). A URL under one names no real service by construction.
var reservedDocTLDs = []string{".example", ".invalid", ".test", ".localhost"}

// reservedDocDomains are the RFC 2606 second-level documentation domains.
var reservedDocDomains = []string{"example.com", "example.net", "example.org"}

// HarnessLeakPatterns returns the canonical harness-leak pattern set. It is
// exported so the surfaces that judge COMMITTED text — the audit privacy rule and
// the record/docs lint — can run exactly these two without a second copy, and it
// is folded into DefaultPatterns so every scanner consumer inherits them.
//
// Both are hard_fail. A session URL is a live handle on a run, and a footer is a
// policy breach on the one surface (a public forge artefact) whose edit history
// keeps the pre-scrub revision — there is no reading under which either belongs
// in public text, so neither is advisory.
func HarnessLeakPatterns() []Pattern {
	return []Pattern{
		{
			Name: "harness_session_url", Kind: kindHarnessSessionURL,
			Label:    "live agent-session URL",
			Re:       harnessSessionURLRe,
			Severity: SeverityHardFail,
			Skip:     func(m string) bool { return hasReservedDocHost(m) || !hasOpaqueSessionID(m) },
			Suggestion: "remove the session link — it is a live handle on a run, and a forge keeps the " +
				"pre-edit revision of anything posted with it",
		},
		{
			Name: "harness_attribution_footer", Kind: kindHarnessFooter,
			Label:    "tool attribution footer",
			Re:       harnessFooterRe,
			Severity: SeverityHardFail,
			// Line-start, expressed where RE2 cannot: a real footer OCCUPIES its
			// own line, while prose about the ban quotes it mid-sentence. Without
			// this the repository could not document its own rule.
			//
			// "Its own line" ADMITS a list marker and a blockquote marker, which
			// the shell gate's `[[:space:]]*` anchor does not. That gate guards
			// commit messages and pull-request bodies against a harness APPEND,
			// which always lands at column 0; this class also covers the
			// model-authored footer, which naturally lands in a bullet or inside
			// a quoted reply. Prose before the match is still a skip, so the
			// writable-about property is unchanged.
			//
			// The reserved-host arm reads the footer's OWN link target, not the
			// rest of the line: scanning the remainder let an unrelated
			// example.com link later in the line disarm a genuine footer.
			SkipAt: func(line string, start, end int) bool {
				return !footerOwnsItsLine(line, start) ||
					hasReservedDocHost(footerLinkTarget(line, end))
			},
			Suggestion: "replace the tool footer with the repository's own disclosure trailer " +
				"(Assisted-by: <Vendor>:<model-version>)",
		},
	}
}

// IsHarnessLeakKind reports whether a finding kind belongs to the harness-leak
// class. It is the selector the outbound scrub and the lint surfaces key on, so
// membership is declared once here rather than by each of them matching strings.
func IsHarnessLeakKind(kind string) bool {
	switch kind {
	case kindHarnessSessionURL, kindHarnessFooter:
		return true
	}
	return false
}

// footerOwnsItsLine reports whether only footerLinePrefixRe's indentation and
// markers precede a footer match at start. Every byte that regex admits is in
// footerPrefixByte, so the walk back stops at the first byte of prose and the
// regex runs only over a prefix made entirely of markers: running it over the
// whole line before every match cost the line's length per footer
// (iss-2609251535277823).
func footerOwnsItsLine(line string, start int) bool {
	i := start
	for i > 0 && footerPrefixByte(line[i-1]) {
		i--
	}
	scanMeter.charge(stageSkipAt, start-i)
	return i == 0 && footerLinePrefixRe.MatchString(line[:start])
}

// footerPrefixByte is every byte footerLinePrefixRe can match.
func footerPrefixByte(b byte) bool {
	switch b {
	case ' ', '\t', '>', '-', '*', '+', '.':
		return true
	}
	return isASCIIDigit(b)
}

// maxFooterLinkText bounds how far past the matched `generated with [` the link
// target is looked for. A footer's link text is a tool's name; the bound keeps
// a line packed with footer openings from searching the rest of the line for
// every one of them (iss-2609251535277823). A target beyond it is not found, so
// the reserved-host exemption does not apply and the footer is reported.
const maxFooterLinkText = 256

// footerLinkTarget returns the target of the markdown link the footer opens —
// the `…](TARGET)` that follows the matched `generated with [`. It is the only
// URL the reserved-documentation test may consider: a footer is not excused by
// some other link further along the line.
func footerLinkTarget(line string, end int) string {
	rest := line[end:]
	window := rest
	if len(window) > maxFooterLinkText+2 {
		window = window[:maxFooterLinkText+2]
	}
	i := strings.Index(window, "](")
	if i < 0 {
		scanMeter.charge(stageSkipAt, len(window))
		return ""
	}
	scanMeter.charge(stageSkipAt, i+2)
	target := rest[i+2:]
	if j := strings.IndexAny(target, ") \t"); j >= 0 {
		target = target[:j]
	}
	scanMeter.charge(stageSkipAt, len(target))
	return target
}

// hasOpaqueSessionID reports whether a candidate session URL ends in an id that
// is actually opaque, rather than in ordinary hyphenated English that happens to
// follow the word "session".
//
// The three accepted shapes are the ones a harness mints: a UUID; a base62 token
// (which always carries both a digit and an upper-case letter — English prose in
// a URL slug is lower-case); and a long lower-case hex run. Everything else is a
// documentation slug, and calling one a leak would flag every page written about
// session handling — including this repository's own research notes, which is
// where the case was found.
//
// COVERAGE BOUNDARY, stated rather than implied (iss-2608281948217899). An id
// that is all lower-case and not all hex — "session_zk3n9q2mvx8rtq" — is NOT
// detected, digits or not. That is the price of sparing the slugs above: a
// lower-case slug with a digit in it ("session-guide-2026") is exactly what a
// documentation URL looks like, and nothing structural tells the two apart.
// Whether a covered harness mints such an id is a fact about services outside
// this repository, so the boundary is the rule's stated contract: a harness
// whose ids take that shape is not covered here, and covering it means naming
// its host rather than widening this test. TestHarnessSessionURLCoverageBoundary
// pins the boundary so it moves only on purpose.
func hasOpaqueSessionID(match string) bool {
	m := sessionIDTailRe.FindStringSubmatch(match)
	if m == nil {
		return false
	}
	id := m[1]
	if sessionUUIDRe.MatchString(id) {
		return true
	}
	digits, upper, hex := 0, 0, true
	for _, r := range id {
		switch {
		case r >= '0' && r <= '9':
			digits++
		case r >= 'A' && r <= 'Z':
			upper++
			hex = false
		case r >= 'a' && r <= 'f':
		default:
			hex = false
		}
	}
	if digits > 0 && upper > 0 {
		return true
	}
	return hex && digits >= 4 && len(id) >= 16
}

// hasReservedDocHost reports whether text carries an http(s) URL whose host is a
// reserved documentation name (RFC 2606/6761). Such a value is illustrative by
// convention — the same reasoning the network patterns' documentation ranges rest
// on — so a page that shows the banned shape is not itself a violation of it.
//
// It reads the URL's HOST rather than looking for the reserved words anywhere in
// the text: a substring test would let the bare word "test" in a sentence excuse
// a real footer on the same line.
func hasReservedDocHost(text string) bool {
	for _, m := range urlHostRe.FindAllStringSubmatch(text, -1) {
		host := strings.ToLower(strings.TrimSuffix(m[1], "."))
		for _, tld := range reservedDocTLDs {
			if strings.HasSuffix(host, tld) {
				return true
			}
		}
		for _, d := range reservedDocDomains {
			if host == d || strings.HasSuffix(host, "."+d) {
				return true
			}
		}
	}
	return false
}
