#!/usr/bin/env bash
# Test corpus for check-attribution.sh's body check.
#
# iss-214 asked for this specifically: the regex must be proven against the
# trailer forms ACTUALLY IN USE in this repository's history, not only against
# the happy path it was written from. `git log` over the record at the time of
# writing shows claude-fable-5 (256), claude-opus-4-8 (225), claude-opus-5 (123),
# claude-opus-5[1m] (33), claude-sonnet-5 (12) and claude-opus-4-8[1m] (5) — the
# bracketed context-window forms are ordinary history, and the first cut of the
# gate rejected every one of them.
#
# Run: bash scripts/check-attribution-cases.sh   (exit 0 all pass, 1 otherwise)
set -uo pipefail

# Hermetic git (iss-28, iss-313): every scratch-repo command below is `git -C
# "$repo" …`, but an inherited absolute GIT_DIR overrides -C and redirects the
# harness's commits and `reset --hard` onto the ambient repository — which then
# reports all-green while rewriting real history. An inherited GIT_CONFIG_GLOBAL
# with commit.gpgsign can also break the scratch commits and skew every case.
# Neutralise the ambient git environment before the first git call. This also
# makes the corpus config-independent, matching gitutil.IsolatedEnv and the
# pre-push hook's unset.
unset GIT_DIR GIT_WORK_TREE GIT_INDEX_FILE GIT_OBJECT_DIRECTORY \
	GIT_ALTERNATE_OBJECT_DIRECTORIES GIT_CONFIG GIT_CONFIG_COUNT GIT_CONFIG_PARAMETERS
export GIT_CONFIG_GLOBAL=/dev/null GIT_CONFIG_NOSYSTEM=1 GIT_TERMINAL_PROMPT=0

cd "$(git rev-parse --show-toplevel)"

SCRIPT=scripts/check-attribution.sh
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

pass=0
fail=0

# case <want:accept|reject> <label> <body-text>
case_is() {
	local want="$1" label="$2" body="$3" got
	printf '%s\n' "$body" >"$tmp/body.md"
	if bash "$SCRIPT" body "$tmp/body.md" >/dev/null 2>&1; then got=accept; else got=reject; fi
	if [ "$got" = "$want" ]; then
		pass=$((pass + 1))
	else
		fail=$((fail + 1))
		echo "FAIL: $label — wanted $want, got $got" >&2
	fi
}

# --- Accepted: every trailer form this repository's history actually uses ------
case_is accept "plain model version" 'Text.

Assisted-by: Claude:claude-opus-5'
case_is accept "bracketed context suffix (iss-214)" 'Text.

Assisted-by: Claude:claude-opus-5[1m]'
case_is accept "bracketed, earlier model (iss-214)" 'Text.

Assisted-by: Claude:claude-opus-4-8[1m]'
case_is accept "dotted/dashed version" 'Text.

Assisted-by: Claude:claude-sonnet-5'
# The positive check is deliberately vendor-agnostic (iss-215): the convention is
# <Vendor>:<model-version>, with Claude an example rather than the literal.
case_is accept "another vendor" 'Text.

Assisted-by: OpenAI:gpt-5'

# --- Rejected -----------------------------------------------------------------
# Correct per iss-214, recorded so it is not re-raised as a defect: the
# convention requires a model VERSION, so a bare vendor is non-conformant.
case_is reject "vendor with no version" 'Text.

Assisted-by: Claude'
case_is reject "no trailer at all" 'Just prose, nothing else.'
case_is reject "tool footer, markdown link" 'Text.

🤖 Generated with [Some Tool](https://example.invalid)

Assisted-by: Claude:claude-opus-5'
case_is reject "tool footer, no emoji" 'Text.

Generated with [Some Tool](https://example.invalid)

Assisted-by: Claude:claude-opus-5'
case_is reject "tool footer, generated BY" 'Text.

Generated by [Some Tool](https://example.invalid)

Assisted-by: Claude:claude-opus-5'
# iss-262: the footer shape a hosted agent platform actually appends is WRAPPED IN
# MARKDOWN EMPHASIS. The first cut anchored on optional whitespace only, so the
# exact form that motivated this gate — a leading underscore — sailed through the
# body check. Found live on two pull requests whose failing leg was something else
# entirely, which is how it went unnoticed.
case_is reject "tool footer, italic underscore (iss-262)" 'Text.

_Generated by [Some Tool](https://example.invalid)_

Assisted-by: Claude:claude-opus-5'
case_is reject "tool footer, italic asterisk (iss-262)" 'Text.

*Generated with [Some Tool](https://example.invalid)*

Assisted-by: Claude:claude-opus-5'
case_is reject "tool footer, bold (iss-262)" 'Text.

**Generated with [Some Tool](https://example.invalid)**

Assisted-by: Claude:claude-opus-5'
case_is reject "tool footer, italic with emoji (iss-262)" 'Text.

_🤖 Generated with [Some Tool](https://example.invalid)_

Assisted-by: Claude:claude-opus-5'
case_is reject "tool footer, italic after a rule (iss-262)" 'Text.

---
_Generated by [Some Tool](https://example.invalid)_

Assisted-by: Claude:claude-opus-5'
# The emoji may sit OUTSIDE the emphasis run as readily as inside it, and
# bold-italic is three markers, not two. Both forms are ordinary markdown and both
# evaded the first cut of this widening — each is one character class away from
# the forms above, so pin them rather than wait to meet them in the wild.
case_is reject "tool footer, emoji outside the emphasis (iss-262)" 'Text.

🤖 _Generated with [Some Tool](https://example.invalid)_

Assisted-by: Claude:claude-opus-5'
case_is reject "tool footer, bold-italic asterisks (iss-262)" 'Text.

***Generated with [Some Tool](https://example.invalid)***

Assisted-by: Claude:claude-opus-5'
case_is reject "tool footer, bold-italic underscores (iss-262)" 'Text.

___Generated by [Some Tool](https://example.invalid)___

Assisted-by: Claude:claude-opus-5'
# The emphasis marker must be attached to the word, exactly as markdown reads it:
# `*text*` is emphasis, `* text` is a LIST ITEM. A bullet describing the banned
# footer is documentation, the same as the `-` bullet form the anchor already
# admits — widening to emphasis must not quietly start rejecting list items.
case_is accept "asterisk BULLET describing the footer (not emphasis)" '* Generated by [Some Tool](https://example.invalid) is the footer we refuse.

Assisted-by: Claude:claude-opus-5'
case_is accept "hyphen bullet describing the footer" '- Generated with [Some Tool](https://example.invalid) is refused.

Assisted-by: Claude:claude-opus-5'
# iss-215: the co-authorship ban must match the trailer KEY, not one vendor's
# name — an AI co-author line wearing another vendor's name was passing.
case_is reject "AI co-author, another vendor" 'Text.

Co-authored-by: ChatGPT <bot@openai.invalid>
Assisted-by: OpenAI:gpt-5'
case_is reject "AI co-author, this vendor" 'Text.

Co-Authored-By: Claude <noreply@anthropic.invalid>
Assisted-by: Claude:claude-opus-5'

# The gate must be writable-about. A footer occupies its own line; prose quoting
# the banned form mid-sentence is documentation, not a footer. Unanchored, the
# rule rejected the very commit that introduced it (and would reject this file,
# the CHANGELOG entry and the issue records).
case_is accept "prose quoting the banned footer" 'We ban the "Generated with [tool](url)" footer, and "Generated by [tool](url)" too.

Assisted-by: Claude:claude-opus-5'
case_is accept "prose quoting the co-author ban" 'The rule is that no Co-authored-by: line may name an AI. See AGENTS.md.

Assisted-by: Claude:claude-opus-5'

# --- Fenced code blocks are quoted material, not the document's own voice ------
# iss-268: mid-sentence prose was the ONLY way to document the banned shape, so a
# fenced example — the natural way to show a literal — was refused exactly as a
# real footer would be. This PR's own first description tripped it. A fenced block
# is quotation, so the rule reads both directions: a banned form inside one is an
# example, and the required trailer inside one is an example too (it cannot serve
# as the declaration).
case_is accept "banned footer inside a fenced block (iss-268)" 'The footer we refuse looks like this:

```
_Generated by [Some Tool](https://example.invalid)_
```

Assisted-by: Claude:claude-opus-5'
case_is accept "co-author ban inside a fenced block (iss-268)" 'Never write:

```
Co-authored-by: Claude <noreply@anthropic.invalid>
```

Assisted-by: Claude:claude-opus-5'
case_is accept "tilde fence (iss-268)" 'Shown with tildes:

~~~
Generated with [Some Tool](https://example.invalid)
~~~

Assisted-by: Claude:claude-opus-5'
case_is accept "fence indented up to three spaces (iss-268)" 'Indented example:

   ```
   _Generated by [Some Tool](https://example.invalid)_
   ```

Assisted-by: Claude:claude-opus-5'
# The trailer must be the document speaking. One that exists only as an example
# inside a fence is not a disclosure, so the body still has none.
case_is reject "trailer ONLY inside a fence is not a declaration (iss-268)" 'How to disclose:

```
Assisted-by: Claude:claude-opus-5
```'
# Stripping the quotation must not hide anything outside it.
case_is reject "real footer after a closed fence (iss-268)" 'An example:

```
some code
```

_Generated by [Some Tool](https://example.invalid)_

Assisted-by: Claude:claude-opus-5'
case_is reject "real footer before a closed fence (iss-268)" '_Generated by [Some Tool](https://example.invalid)_

```
some code
```

Assisted-by: Claude:claude-opus-5'
# An UNCLOSED fence fails closed. Markdown renders the rest of the document as
# code, so honouring it would let one stray fence line suppress every check below
# it — the cheapest possible bypass. An unbalanced document is quoted nowhere.
# The trailer sits BEFORE the stray fence and the footer after it, so honouring an
# unclosed fence would strip the footer and leave a compliant-looking body — the
# case had to be shaped this way to discriminate. Rejecting for a missing trailer
# would pass whether the fence was honoured or not, and prove nothing.
case_is reject "unclosed fence does not suppress the check (iss-268)" 'Assisted-by: Claude:claude-opus-5

Oops, never closed:

```
_Generated by [Some Tool](https://example.invalid)_
'
# The stripped region must be a SUBSET of what markdown renders as code. A line the
# gate skips but the forge renders as an ordinary paragraph IS a real footer,
# silently passed — which is exactly what a marker-presence test allowed. Each case
# below renders the footer as visible text on the forge; each was confirmed to pass
# the gate before the matcher became pairing-aware.
case_is reject "type skew: a tilde block is not closed by backticks (iss-268)" 'Text.

~~~
```
~~~
🤖 _Generated with [Some Tool](https://example.invalid)_
```

Assisted-by: Claude:claude-opus-5'
case_is reject "length skew: a closer must be at least as long as its opener (iss-268)" 'Text.

````
```
````
🤖 _Generated with [Some Tool](https://example.invalid)_
```

Assisted-by: Claude:claude-opus-5'
# No exotic markdown at all: a backtick fence's info string may not contain a
# backtick, so both scaffolding lines are inline code spans and the whole thing is
# ONE paragraph with the footer rendered in full.
case_is reject "inline code spans are not fences (iss-268)" '```make preflight``` is the gate.
🤖 _Generated with [Some Tool](https://example.invalid)_
```make build``` builds it.

Assisted-by: Claude:claude-opus-5'
# Isolating the info-string guard. The case above rejects for TWO reasons at once
# (the span is not an opener, AND the block never terminates), so it cannot tell
# the guard apart from the fail-closed path. Here a later bare marker WOULD close
# the block, so dropping the guard alone strips the footer and passes.
case_is reject "an inline span must not open a block a later marker closes (iss-268)" '```make``` is the gate.
🤖 _Generated with [Some Tool](https://example.invalid)_
```

Assisted-by: Claude:claude-opus-5'
# Isolating the closer's bare-marker requirement: a marker carrying an info string
# is content, not a closer, so the block runs on and the footer inside it is
# quotation. Treating it as a closer would end the block early and expose the
# footer — the opposite direction, but the same drift away from what markdown does.
case_is accept "a marker with an info string does not close a block (iss-268)" 'Two shapes:

```
```text
_Generated by [Some Tool](https://example.invalid)_
```

Assisted-by: Claude:claude-opus-5'
# A run shorter than three is not a fence in markdown — it is ordinary text, and
# the lines between two such runs render in full.
case_is reject "a two-character run is not a fence (iss-268)" 'Text.

``
🤖 _Generated with [Some Tool](https://example.invalid)_
``

Assisted-by: Claude:claude-opus-5'
case_is reject "a two-tilde run is not a fence (iss-268)" 'Text.

~~
_Generated by [Some Tool](https://example.invalid)_
~~

Assisted-by: Claude:claude-opus-5'

# --- Clauses the corpus was not pinning (iss-271) -------------------------------
# The marker-character test restricts a fence delimiter to backtick or tilde.
# Substituting a bare emptiness check keeps the matcher terminating and leaves the
# rest of this corpus green, yet --- *** ___ === runs then become fence
# delimiters — a setext heading or a thematic break would start stripping. That is
# the one unpinned clause with a bypass direction.
case_is reject "a dash run is not a fence delimiter (iss-271)" 'Heading
---
🤖 _Generated with [Some Tool](https://example.invalid)_
---

Assisted-by: Claude:claude-opus-5'
case_is reject "an asterisk run is not a fence delimiter (iss-271)" 'Text.

***
_Generated by [Some Tool](https://example.invalid)_
***

Assisted-by: Claude:claude-opus-5'
case_is reject "an underscore run is not a fence delimiter (iss-271)" 'Text.

___
_Generated by [Some Tool](https://example.invalid)_
___

Assisted-by: Claude:claude-opus-5'
# The opener indent is measured in SPACES only. A tab-led line is an indented code
# block in markdown, not a fence, so it must not open one.
case_is reject "a tab-led marker is not a fence (iss-271)" 'Text.

	```
🤖 _Generated with [Some Tool](https://example.invalid)_
	```

Assisted-by: Claude:claude-opus-5'
# A closer may carry trailing whitespace — spaces, tabs, and the \r of a CRLF
# line ending — and still close. Narrowing that set would leave the block open,
# and the unterminated rule would then refuse the whole strip.
case_is accept "a closer with trailing tab still closes (iss-271)" 'Example:

```
_Generated by [Some Tool](https://example.invalid)_
```	

Assisted-by: Claude:claude-opus-5'
# iss-270 is pinned for `- ` items; a `1. ` item's content sits at column 3,
# also under the limit, so it is the same class and needs the same pin.
case_is accept "KNOWN: a fence inside an ordered list item too (iss-270)" '1. item
   ```

🤖 _Generated with [Some Tool](https://example.invalid)_

   ```

Assisted-by: Claude:claude-opus-5'
# Nothing placed a checkable line immediately after a closer, so a one-line
# over-strip at the boundary passed the whole corpus.
case_is reject "the line straight after a closer is still checked (iss-271)" 'Example:

```
x
```
🤖 _Generated with [Some Tool](https://example.invalid)_

Assisted-by: Claude:claude-opus-5'

# --- The property that is actually load-bearing --------------------------------
# This gate exists because bodies picked up a tool's DEFAULT footer across 78 pull
# requests (itd-91) — an accident at scale, not an adversary. A tool appends its
# footer LAST, so "a footer after the content is caught whatever precedes it" is
# the invariant worth pinning. It holds because no fence opened earlier can still
# be open at the end without the unterminated rule refusing the whole strip.
case_is reject "footer last, after a closed fence (itd-91)" 'Text.

```
example
```

Assisted-by: Claude:claude-opus-5

🤖 _Generated with [Some Tool](https://example.invalid)_'
case_is reject "footer last, after a tilde block with an info string (itd-91)" 'Text.

~~~markdown
example
~~~

Assisted-by: Claude:claude-opus-5

---
_Generated by [Some Tool](https://example.invalid)_'
case_is reject "footer last, after several blocks (itd-91)" 'One.

````
```
````

Two.

~~~
x
~~~

Assisted-by: Claude:claude-opus-5
🤖 Generated with [Some Tool](https://example.invalid)'

# --- Block containers the matcher cannot model ---------------------------------
# It is line-based and has no model of markdown's block containers, so a fence
# opened inside one is read as document-level and the span it closes over is
# removed while the forge renders part of that span as an ordinary paragraph.
# An HTML block would do this, so a document containing one strips NOTHING —
# striking less can only over-reject, so the guard is safe by construction.
case_is reject "HTML comment cannot camouflage a fence (iss-268)" '<!--
~~~
-->
🤖 _Generated with [Some Tool](https://example.invalid)_
~~~

Assisted-by: Claude:claude-opus-5'
case_is reject "HTML block cannot camouflage a fence (iss-268)" '<div>
```
</div>
🤖 _Generated with [Some Tool](https://example.invalid)_
```

Assisted-by: Claude:claude-opus-5'
# KNOWN RESIDUAL, pinned so a future fix is visible rather than silent. A
# first-level `- ` item's content sits at column 2, under the three-space limit,
# so its fence is read as document-level and the footer between the markers is
# stripped although the forge renders it as a paragraph. ACCEPTED by decision in
# iss-270 rather than outstanding, so this case exists to make a change to that
# behaviour visible, not to mark a defect awaiting a fix. This is an
# instance of "a body constructed around the footer", which the design already
# declines to defend against — not a new class — and the footer-last cases above
# are what stands between this gate and the accident it was built for.
case_is accept "KNOWN: a fence inside a list item is read as document-level (iss-270)" '- item
  ```

🤖 _Generated with [Some Tool](https://example.invalid)_

```

Assisted-by: Claude:claude-opus-5'

# An info string is what essentially every real fence carries; a matcher that
# demanded a bare marker would strip nothing in practice and reinstate iss-268.
case_is accept "fence carrying an info string (iss-268)" 'The shape we refuse:

```text
_Generated by [Some Tool](https://example.invalid)_
```

Assisted-by: Claude:claude-opus-5'
# Documenting the fence rule itself needs a longer outer fence around a shorter
# inner one. Counting markers saw three and failed closed on the very shape this
# change exists to enable; tracking the opener reads it as one block.
case_is accept "nested fence: a four-tick block quoting a three-tick example (iss-268)" 'How to document it:

````
```
_Generated by [Some Tool](https://example.invalid)_
```
````

Assisted-by: Claude:claude-opus-5'
# A tab-indented or deeply-indented line is not a fence in markdown, so it is not
# quotation and the gate still applies — the conservative reading.
case_is reject "four-space indent is not a fence (iss-268)" 'Indented four:

    ```
    _Generated by [Some Tool](https://example.invalid)_
    ```

Assisted-by: Claude:claude-opus-5'

# --- Not a shell --------------------------------------------------------------
# The body is attacker-controlled text; it must never be evaluated.
case_is accept "body containing shell metacharacters" 'evil $(touch '"$tmp"'/PWNED) `id` ${IFS}

Assisted-by: Claude:claude-opus-5'
if [ -e "$tmp/PWNED" ]; then
	echo "FAIL: body containing shell metacharacters — the body was EXECUTED" >&2
	fail=$((fail + 1))
fi

# --- The git identity itself (commits mode) -----------------------------------
# The contributor graph is built from commit AUTHORSHIP plus Co-authored-by
# trailers, not from messages alone. A commit authored as
# `Claude <noreply@anthropic.com>` with a fully compliant message sailed through
# the message-only gate, put an AI at #2 in the contributor graph, and — because
# a squash merge auto-appends a Co-authored-by for any branch author who is not
# the PR author — inflated it again on every squash of that branch. These cases
# prove the commits half reads the identity, not only the message.
repo="$tmp/repo"
git init -q "$repo"
git -C "$repo" -c user.name=REPPL -c user.email=human@example.invalid \
	commit -q --allow-empty -m 'base'
base="$(git -C "$repo" rev-parse HEAD)"
SCRIPT_ABS="$(pwd)/$SCRIPT"

# commits_case <want> <label> — checks base..HEAD in the scratch repo, then resets.
commits_case() {
	local want="$1" label="$2" got
	if (cd "$repo" && bash "$SCRIPT_ABS" commits "$base" HEAD >/dev/null 2>&1); then
		got=accept
	else
		got=reject
	fi
	if [ "$got" = "$want" ]; then
		pass=$((pass + 1))
	else
		fail=$((fail + 1))
		echo "FAIL: $label — wanted $want, got $got" >&2
	fi
	git -C "$repo" reset -q --hard "$base"
}

# commit_as <author-name> <author-email> <committer-name> <committer-email> <msg>
commit_as() {
	GIT_AUTHOR_NAME="$1" GIT_AUTHOR_EMAIL="$2" \
		GIT_COMMITTER_NAME="$3" GIT_COMMITTER_EMAIL="$4" \
		git -C "$repo" commit -q --allow-empty -m "$5" || {
		echo "FAIL: could not create the scratch commit (git config leak?)" >&2
		exit 1
	}
}

MSG_OK='Text.

Assisted-by: Claude:claude-opus-5'

commit_as REPPL human@example.invalid REPPL human@example.invalid "$MSG_OK"
commits_case accept "human identity, compliant message"

# The bf68242 case: identity is the AI, message is fully compliant.
commit_as Claude noreply@anthropic.com Claude noreply@anthropic.com "$MSG_OK"
commits_case reject "AI author and committer, compliant message"

commit_as REPPL human@example.invalid Claude noreply@anthropic.com "$MSG_OK"
commits_case reject "AI committer only, compliant message"

commit_as Claude claude@example.invalid REPPL human@example.invalid "$MSG_OK"
commits_case reject "AI author by name alone, compliant message"

# Vendor-agnostic, as with the co-authorship ban (iss-215).
commit_as ChatGPT bot@openai.com REPPL human@example.invalid "$MSG_OK"
commits_case reject "another vendor's AI author, compliant message"

# A human whose name merely CONTAINS an AI name is not an AI identity.
commit_as 'Claudette Martin' claudette@example.invalid 'Claudette Martin' claudette@example.invalid "$MSG_OK"
commits_case accept "human name containing an AI name"

# --- Machines are refused; humans are not (iss-2609082001204831) ---------------
# The rule the maintainer states is refuse-machines-allow-humans, NOT an allowlist
# of one name: this repository takes outside contributions (.abcd/work/intake.md)
# and already carries a commit from an outside human. A commit is authored by a
# human and machine assistance is disclosed by the trailer alone, so the signal
# has to be STRUCTURAL — the forge's own `[bot]` name suffix and the bot mailbox
# shape it stamps — rather than a roster of tool names, which only ever grows.
#
# The exemption these cases replace was the second of the two holes: a machine
# identity that is not an AI VENDOR matched neither identity list, so three
# dependabot[bot] commits authored dependency bumps directly into main. The
# exemption's own reasoning ("failing its PRs would train the maintainer to
# discount a red gate") is answered by the consequence rather than by the gate: a
# dependency bump is landed by a human, and the gate is correct to be red until
# one does.
commit_as 'dependabot[bot]' '49699333+dependabot[bot]@users.noreply.github.com' \
	'GitHub' 'noreply@github.com' 'chore(deps): bump something'
commits_case reject "bot author, forge bot mailbox"

# The `[bot]` suffix is the signal, not the name that carries it — a second
# automation appears in the right place without an edit here.
commit_as 'renovate[bot]' 'renovate[bot]@users.noreply.github.com' \
	REPPL human@example.invalid "$MSG_OK"
commits_case reject "another bot author, compliant message"

# A machine COMMITTER on a human-authored commit is refused too. The graph reads
# authorship, but a bot that commits on a human's behalf is a route back to the
# same place, and the existing AI-committer case already settled the principle.
commit_as REPPL human@example.invalid \
	'dependabot[bot]' '49699333+dependabot[bot]@users.noreply.github.com' "$MSG_OK"
commits_case reject "human author, bot committer"

# THE DISCRIMINATOR, and the case most worth getting right: a forge PRIVACY
# address is a PERSON'S address. `1234+name@users.noreply.github.com` is how the
# overwhelming majority of this repository's own commits are authored — the host
# says noreply, the mailbox is the account. `[bot]` in the mailbox is what makes
# `49699333+dependabot[bot]@users.noreply.github.com` a machine, never the host.
# Reading the host instead would refuse every human here.
commit_as 'Ada Lovelace' '1234+ada@users.noreply.github.com' \
	'Ada Lovelace' '1234+ada@users.noreply.github.com' "$MSG_OK"
commits_case accept "human at a forge privacy address"

# The older form of the same address, with no numeric prefix — the outside
# contributor this repository already carries commits from.
commit_as 'Ethan Hawkes' 'ethanhawkes-gif@users.noreply.github.com' \
	'Ethan Hawkes' 'ethanhawkes-gif@users.noreply.github.com' "$MSG_OK"
commits_case accept "outside human contributor, forge address"

# Two different humans in one range is the ordinary shape of an accepted
# contribution, and an allowlist of one name would refuse it.
commit_as REPPL human@example.invalid REPPL human@example.invalid "$MSG_OK"
commit_as 'Ada Lovelace' '1234+ada@users.noreply.github.com' \
	'Ada Lovelace' '1234+ada@users.noreply.github.com' "$MSG_OK"
commits_case accept "two different human authors"

# The forge as COMMITTER is not a machine author: every merge and squash made
# through the web UI is committed by `GitHub <noreply@github.com>` on a human's
# click, and 638 commits in this repository's main are shaped exactly so.
# Refusing a `noreply@` mailbox in the committer role would turn the whole
# history red — which is why the mailbox rule is asymmetric between the roles.
commit_as 'Alex Reppel' '77722411+REPPL@users.noreply.github.com' \
	'GitHub' 'noreply@github.com' "$MSG_OK"
commits_case accept "forge committer on a human-authored commit"

# --- Merge commits carry an identity too (iss-2609082001204831) ----------------
# The first hole: the commits arm walked `--no-merges`, so a merge commit's
# identity was never read at all. 23f0a891 stands in main today, authored AND
# committed as `Claude <noreply@anthropic.com>` — a merge made by an autonomous
# round running with the tool's own git identity, which is precisely the shape
# the identity check exists to refuse and the one shape it could not see.
#
# merge_as <author-name> <author-email> <committer-name> <committer-email> <msg>
# builds a real two-parent merge on top of $base and leaves HEAD on the trunk.
#
# The two side commits carry DIFFERENT messages, and that is not cosmetic: an
# empty commit is fully determined by its tree, parent, message, identity and
# timestamp, so two identical ones made in the same second are the SAME OBJECT.
# With one message the branches converged on a single sha, `--no-ff` had nothing
# to merge, and the case silently tested a fast-forward — a green merge case that
# contained no merge.
mainb="$(git -C "$repo" rev-parse --abbrev-ref HEAD)"
merge_as() {
	git -C "$repo" checkout -q -B side "$base"
	commit_as REPPL human@example.invalid REPPL human@example.invalid "on the branch

Assisted-by: Claude:claude-opus-5"
	git -C "$repo" checkout -q "$mainb"
	commit_as REPPL human@example.invalid REPPL human@example.invalid "on the trunk

Assisted-by: Claude:claude-opus-5"
	GIT_AUTHOR_NAME="$1" GIT_AUTHOR_EMAIL="$2" \
		GIT_COMMITTER_NAME="$3" GIT_COMMITTER_EMAIL="$4" \
		git -C "$repo" merge -q --no-ff -m "$5" side || {
		echo "FAIL: could not create the scratch merge" >&2
		exit 1
	}
	# A merge case that contains no merge proves nothing; assert the shape.
	if [ "$(git -C "$repo" show -s --format='%P' HEAD | wc -w)" -lt 2 ]; then
		echo "FAIL: the scratch merge is not a merge commit" >&2
		exit 1
	fi
}

merge_as Claude noreply@anthropic.com Claude noreply@anthropic.com 'Merge branch side'
commits_case reject "merge commit authored by an AI identity (23f0a891)"

merge_as 'dependabot[bot]' '49699333+dependabot[bot]@users.noreply.github.com' \
	'GitHub' 'noreply@github.com' 'Merge branch side'
commits_case reject "merge commit authored by a bot"

# A merge commit's MESSAGE is still exempt, and that exemption is now the only
# one left: `Merge pull request #N from …` is composed by the forge and carries
# no trailer of its own, so checking its text would turn every merge in this
# repository red. Identity and message are separable, and only the message half
# was ever generated elsewhere.
merge_as 'Alex Reppel' '77722411+REPPL@users.noreply.github.com' \
	'GitHub' 'noreply@github.com' 'Merge pull request #1 from intentdriven/side'
commits_case accept "forge merge commit, human author, no trailer"

# --- The human-only declaration -----------------------------------------------
# A change no AI touched discloses that positively; silence stays refused,
# because an absent trailer and a forgotten one are indistinguishable.
case_is accept "human-only declaration" 'A change I wrote by hand.

Assisted-by: None'
case_is accept "human-only declaration, lower case" 'A change I wrote by hand.

Assisted-by: none'
case_is reject "still no trailer at all" 'A change with nothing disclosed.'
# The declaration is a closed value, not a free-text escape: anything else in
# the slot would reopen the omission it exists to close.
case_is reject "free-text escape is not a declaration" 'Text.

Assisted-by: n/a'
case_is reject "free-text escape (human)" 'Text.

Assisted-by: human'
case_is reject "None with trailing prose is not the declaration" 'Text.

Assisted-by: None really'
# The declaration never licenses the banned forms.
case_is reject "declaration alongside a co-authorship trailer" 'Text.

Assisted-by: None
Co-authored-by: Someone <someone@example.invalid>'
case_is reject "declaration alongside a generated-with footer" 'Text.

🤖 Generated with [Some Tool](https://example.invalid)

Assisted-by: None'

# A human-only COMMIT passes the commit check on the same terms.
commit_as REPPL human@example.invalid REPPL human@example.invalid 'docs: a hand-written change

Assisted-by: None'
commits_case accept "human-only commit declaration"

# Fenced quotation is a BODY concession only. The justification is that a forge
# renders a fence as a code block, so it reads as an example — and a commit message
# is never rendered as markdown. `git log` shows it verbatim, so a fenced footer
# there is displayed exactly as a real one and lands in permanent history.
commit_as REPPL human@example.invalid REPPL human@example.invalid 'docs: a change

```
🤖 Generated with [Some Tool](https://example.invalid)
Co-authored-by: Claude <noreply@anthropic.invalid>
```

Assisted-by: Claude:claude-opus-5'
commits_case reject "a fenced footer in a COMMIT MESSAGE is still refused (iss-268)"

# An AI identity is still refused even when the message declares human-only —
# the identity fields are what the contributor graph reads.
commit_as Claude noreply@anthropic.com REPPL human@example.invalid 'docs: a change

Assisted-by: None'
commits_case reject "AI identity claiming human-only"

# --- CRLF bodies (GitHub web-UI line endings) ---------------------------------
# A PR body authored or edited in the web UI arrives with \r\n. A valid trailer
# that is not the very last byte reads as "Assisted-by: ...\r" and must still be
# accepted (the gate normalises \r before the $-anchored presence check); a
# banned footer under CRLF must still reject. case_is_crlf rewrites the body to
# CRLF via awk (portable across GNU and BSD).
case_is_crlf() {
	local want="$1" label="$2" body="$3" got
	printf '%s\n' "$body" | awk 'BEGIN{ORS="\r\n"} {print}' >"$tmp/body.md"
	if bash "$SCRIPT" body "$tmp/body.md" >/dev/null 2>&1; then got=accept; else got=reject; fi
	if [ "$got" = "$want" ]; then
		pass=$((pass + 1))
	else
		fail=$((fail + 1))
		echo "FAIL (crlf): $label — wanted $want, got $got" >&2
	fi
}
case_is_crlf accept "CRLF body, trailer not the final byte" 'Text.

Assisted-by: Claude:claude-opus-5'
case_is_crlf accept "CRLF body, human-only declaration" 'Text.

Assisted-by: None'
case_is_crlf reject "CRLF body, tool footer still refused" 'Text.

🤖 Generated with [Some Tool](https://example.invalid)

Assisted-by: Claude:claude-opus-5'

echo "check-attribution-cases: $pass passed, $fail failed"
[ "$fail" -eq 0 ]
