package cli

// The bare-invocation banner (itd-112/spc-41). Decoration renders only on an
// interactive TTY, from trusted-static content — the livery grids and the
// build-time-baked identity text — per adr-49 and brief invariant 13. The
// banner tops the status board; it never replaces it, and no banner byte
// reaches --json, hooks, or a piped stream.

//go:generate go run ./identitygen

import (
	"fmt"
	"io"
	"os"
	"strings"

	"golang.org/x/text/width"

	"github.com/intentdriven/abcd/internal/core"
	"github.com/intentdriven/abcd/internal/livery"
	"github.com/intentdriven/abcd/internal/term"
)

// bannerTTY is the emission seam: under test cmd.OutOrStdout() is a buffer,
// so the banner is off by default everywhere except a real interactive
// terminal. Tests override the seam to exercise the on path (the repo's
// package-var seam pattern).
var bannerTTY = func(w io.Writer) bool {
	f, ok := w.(*os.File)
	return ok && term.IsTerminal(f)
}

// bannerNameSegment renders the identity line's lead: stamped builds carry
// their v-prefixed version, unstamped builds say so honestly.
func bannerNameSegment() string {
	if v := core.Version; v != "" && v != "dev" {
		return "abcd " + v
	}
	return "abcd (dev build)"
}

// bannerLines composes the banner for one ladder rung. Colour rungs: the
// half-block flag hoist with the name beside it, tagline and hints beneath.
// Mono with UTF-8: the five-row shade-block art. No UTF-8: text lines only —
// degraded output is never blank (adr-49).
func bannerLines(mode term.ColorMode, utf8OK bool) []string {
	name := bannerNameSegment()
	tagline := bannerTaglineLines()
	textOnly := append(append([]string{name}, tagline...), "run `abcd --help` to explore · `abcd ahoy` to set up")
	if !utf8OK {
		return textOnly
	}
	logo := bannerLogoAsset()
	if mode == term.Mono {
		lines := livery.RenderShade(logo)
		return append(lines, textOnly...)
	}
	accent, reset := livery.FG('o', mode), livery.Reset
	strip := livery.RenderHalfBlock(logo, mode)
	strip[0] += "  " + accent + name + reset
	lines := append(strip, tagline...)
	hints := "run " + accent + "abcd --help" + reset + " to explore · " + accent + "abcd ahoy" + reset + " to set up"
	return append(lines, hints)
}

// bannerWidth is AC1's fixed layout bound (itd-112): the banner renders
// within 66 columns, with no terminal-width detection.
const bannerWidth = 66

// bannerTaglineLines is the baked tagline wrapped to the banner width at
// render time. The tagline is the canonical identity block's text and is
// never edited to fit: the wrap moves only the line breaks.
func bannerTaglineLines() []string {
	return wrapWords(bakedTagline, bannerWidth)
}

// wrapWords word-wraps s into lines of at most limit display columns and
// never breaks a word; a word wider than limit stands alone on its line. The
// wrap is balanced: it keeps the fewest lines a greedy wrap at limit needs,
// then narrows the measure while that count holds, so the last line is never
// a stranded word.
func wrapWords(s string, limit int) []string {
	words := strings.Fields(s)
	longest := 0
	for _, w := range words {
		longest = max(longest, displayColumns(w))
	}
	lines := greedyWrap(words, limit)
	for measure := limit - 1; measure >= longest; measure-- {
		narrower := greedyWrap(words, measure)
		if len(narrower) > len(lines) {
			break
		}
		lines = narrower
	}
	return lines
}

// greedyWrap fills each line with as many words as fit within limit
// display columns.
func greedyWrap(words []string, limit int) []string {
	var lines []string
	line, cols := "", 0
	for _, w := range words {
		wc := displayColumns(w)
		switch {
		case line == "":
			line, cols = w, wc
		case cols+1+wc <= limit:
			line, cols = line+" "+w, cols+1+wc
		default:
			lines = append(lines, line)
			line, cols = w, wc
		}
	}
	if line != "" {
		lines = append(lines, line)
	}
	return lines
}

// displayColumns counts the terminal columns plain text occupies: East Asian
// wide and fullwidth runes take two, every other rune one.
func displayColumns(s string) int {
	n := 0
	for _, r := range s {
		switch width.LookupRune(r).Kind() {
		case width.EastAsianWide, width.EastAsianFullwidth:
			n += 2
		default:
			n++
		}
	}
	return n
}

// IdentityGenSource is the single template for the generated identity file:
// the identitygen command writes it, and the drift test regenerates and
// byte-compares the committed file against it — one source, so the file can
// drift in neither values nor form (the livery RenderSVG shape).
func IdentityGenSource(title, tagline string) []byte {
	return []byte(fmt.Sprintf(`// Code generated by identitygen; DO NOT EDIT.
// Regenerate with: go generate ./internal/surface/cli
// Source of truth: the canonical identity block (itd-102); the drift test
// TestBakedIdentityInSync holds this file to it byte-for-byte.

package cli

const (
	bakedTitle   = %q
	bakedTagline = %q
)
`, title, tagline))
}

func bannerLogoAsset() livery.Asset {
	for _, a := range livery.Assets() {
		if a.Name == "logo-flags" {
			return a
		}
	}
	// The canonical grids always carry the logo; reaching this is a
	// programming error surfaced by the banner tests, not a runtime path.
	panic("livery: logo-flags asset missing")
}

// writeBanner resolves the ladder from the environment and emits the banner
// plus a separating blank line. getenv is injected so ladder resolution is
// table-testable without touching the process environment.
func writeBanner(w io.Writer, noColor bool, getenv func(string) string) {
	// Blank lines fore and aft: the art breathes instead of hugging the
	// prompt above and the board below.
	fmt.Fprintln(w)
	mode := term.ResolveColorMode(getenv, noColor)
	for _, line := range bannerLines(mode, term.UTF8Locale(getenv)) {
		fmt.Fprintln(w, line)
	}
	fmt.Fprintln(w)
}
